name: Windows MSVC CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    # 1. Fetch your code from GitHub
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Configure environment variables for cl.exe
    - name: Configure Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    # 3. Compile your application using cl
    - name: Build with cl.exe sha256-x86.c
      run: |
        cl.exe /EHsc sha256-x86.c /out:sha256-x86.exe /DTEST_MAIN
        cl /LD sha256-x86.c
    - name: Build with cl.exe sha512.c
      run: |
        cl.exe /EHsc sha512.c  /out:sha512.exe /DTEST_MAIN
        cl /LD sha512.c
    - name: Build with cl.exe sha1-x86.c
      run: |
        cl.exe /EHsc sha1-x86.c  /out:sha1-x86.exe /DTEST_MAIN
        cl /LD sha1-x86.c
    - name: Build with cl.exe cpuid.c
      run: |
        cl.exe /EHsc cpuid.c  /out:cpuid_sha_ni.exe /DTEST_MAIN
        cl /LD cpuid.c /out:cpuid_sha_ni.dll
    # 4. (Optional) Run your generated binary
    - name: Run Executable
      continue-on-error: true
      run: |
        .\sha256-x86.exe
        .\sha1-x86.exe
        .\sha512.exe
        .\cpuid_sha_ni.exe

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v7.0.1
      with:
        # Artifact name. If the `archive` input is `false`, the name of the file uploaded will be the artifact name.
        path: ./
